apiVersion: apps/v1
kind: Deployment
metadata:
  name: minecraft
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minecraft
  template:
    metadata:
      labels:
        app: minecraft
    spec:
      containers:
      - name: minecraft
        image: itzg/minecraft-server
        ports:
        - containerPort: 25565
        resources: 
          requests:
            memory: "1536Mi"
        env:
        - name: VERSION
          value: 1.18.2
        - name: EULA
          value: 'TRUE'
        - name: TYPE
          value: AUTO_CURSEFORGE
        - name: CF_SLUG
          value: vault-hunters-1-18-2
        - name: MEMORY
          value: 1.5G
        - name: DIFFICULTY
          value: normal
        # - name: FORGE_INSTALLER
        #   value: forge-40.1.93.jar
        # - name: FORGE_VERSION
        #   value: 40.1.93
        # - name: FORGE_FORCE_REINSTALL
        #   value: 'true' 
        volumeMounts:
        - name: worlddata
          mountPath: /data
      volumes:
      - name: worlddata
        csi:
          driver: file.csi.azure.com
          readOnly: false
          volumeAttributes:
            secretName: azure-secret
            shareName: worlddata
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    # https://docs.microsoft.com/en-us/azure/aks/static-ip#apply-a-dns-label-to-the-service
    service.beta.kubernetes.io/azure-dns-label-name: minecraft-vaulthunters
  name: minecraft-lb
spec:
  type: LoadBalancer
  ports:
    - port: 25565
      targetPort: 25565
  selector:
    app: minecraft