name: 'static resources deploy'

on:
  push:
    branches:
      - main
    paths:
      - iac/static_resources/**
      - .github/workflows/static_deploy.yml

permissions:
  contents: read

jobs:
  deploy:
    name: 'deploy'
    runs-on: ubuntu-latest
    environment: production
    env:
      ARM_CLIENT_ID: ${{ secrets.AZURE_AD_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.AZURE_AD_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.AZURE_AD_TENANT_ID }}

    defaults:
      run:
        shell: bash

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Terraform Init
      working-directory: iac/static_resources
      run: terraform init

    - name: Terraform Apply
      working-directory: iac/static_resources
      run: terraform apply -auto-approve -input=false
